[tool.poetry]
name = "ai-browser-server"
version = "0.1.0"
description = "Local AI Server"
authors = ["You <you@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "*"
uvicorn = {extras = ["standard"], version = "*"}
pydantic = "*"
python-dotenv = "*"
langchain = "*"
langchain-community = "*"
chromadb = "*"
sentence-transformers = "*"
aiohttp = "^3.13.3"
sqlalchemy = "^2.0.46"
aiosqlite = "^0.22.1"
greenlet = "^3.3.1"
alembic = "^1.18.3"
diskcache = "^5.6.3"
flashrank = "^0.2.10"
beautifulsoup4 = "^4.14.3"

[tool.poetry.group.dev.dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"