from abc import ABC, abstractmethod
from typing import List, Dict, Any, AsyncGenerator

# ==============================================================================
# LLM ADAPTER INTERFACE
# ==============================================================================

class BaseLLMAdapter(ABC):
    """
    Abstract Base Class defining the strict contract for all LLM providers.
    Ensures a uniform API for the manager, regardless of whether the backend 
    is powered by llama.cpp, Ollama, or an external cloud service.
    """
    
    @abstractmethod
    async def initialize(self) -> None:
        """Executes startup routines such as model loading, health checks, or VRAM allocation."""
        pass

    @abstractmethod
    async def generate(self, messages: List[Dict[str, str]], settings: Dict[str, Any]) -> str:
        """
        Executes a standard, blocking text generation request.
        Returns the complete, final response string once generation concludes.
        """
        pass

    @abstractmethod
    async def stream(self, messages: List[Dict[str, str]], settings: Dict[str, Any]) -> AsyncGenerator[str, None]:
        """
        Executes an asynchronous, streaming text generation request.
        Yields text chunks back to the event loop as they are generated by the model.
        """
        pass